version: 2.1

workflows:
  build-deploy:
    jobs:
     - build

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 19.03.14
      - checkout
      - run: 
          name : Build arm64
          command : |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker buildx build --platform=linux/arm64 -t mrseccubus/githubpages:latest --push --progress plain .
      - run: 
          name : Build amd64
          command : |
            docker build -t mrseccubus/githubpages:latest .
