version: 2
jobs:
  build:
    docker:
      - image: jdrouet/docker-with-buildx:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            --progress plain \
            --tag mrseccubus/github-pages:latest . 
