version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: ubuntu
    steps:
#      - run:
#          name: Prerequisites
#          command: |
#            apk update
#            apk add docker-cli git openssh
#      - checkout
#      - setup_remote_docker:
#          docker_layer_caching: true
      - run:
          name: Setup buildx and qemu
          command: |
            sudo apt-get update
            sudo apt-get install -y qemu-user-static
            sudo apt-get install -y binfmt-support
      - run:
          name: Check versions
          command: |
            qemu-aarch64-static --version
            update-binfmts --version 
      - run:
          name: Create builder
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker buildx create --name arm-builder
            docker buildx use arm-builder
            docker buildx inspect --bootstrap      
      - run:
          name: Build application Docker image
          command: |
            docker build -t github-pages .;
            docker tag github-pages mrseccubus/github-pages:latest;
            docker tag github-pages mrseccubus/github-pages:$(cat version.txt).$CIRCLE_BUILD_NUM
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin 
              docker push mrseccubus/github-pages:$(cat version.txt).$CIRCLE_BUILD_NUM
              docker push mrseccubus/github-pages:latest
            fi
      - deploy:
          name: Build ARM docker
          command: | 
            DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --platform linux/arm64 --load -t mrseccbus/github-pages . --push