name: Build

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
  schedule:
    - cron: "5 4 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        if:   ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set versions
        run : |
          VERSION=$(git describe --tags --abbrev=0)
          COUNT=$(git log $VERSION..HEAD --oneline|wc -l|sed -e 's# ##g')
          VERSION=$VERSION.$COUNT
          IFS="."
          echo $VERSION | sed "s/^v//" | read -a VERSION_ARRAY
          MAJOR=${VERSION_ARRAY[0]}
          MINOR=${VERSION_ARRAY[0]}.${VERSION_ARRAY[1]}
          FULL=${VERSION_ARRAY[0]}.${VERSION_ARRAY[1]}.${VERSION_ARRAY[2]}
          echo "MAJOR=${MAJOR}" >> $GITHUB_ENV
          echo "MINOR=${MINOR}" >> $GITHUB_ENV
          echo "FULL=${FULL}" >> $GITHUB_ENV
      - name: Docker meta
        id: seccubus_github_pages # you'll use this in the next step
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            mrseccubus/github-pages
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=${{ env.MAJOR }}
            type=raw,value=${{ env.MINOR }}
            type=raw,value=${{ env.FULL }}
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.url=https://github.com/MrSeccubus/github-pages
            org.opencontainers.image.source=https://github.com/MrSeccubus/github-pages
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.seccubus_github_pages.outputs.tags }}
          labels: ${{ steps.seccubus_github_pages.outputs.labels }}
