name: Build

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
  schedule:
    - cron: "5 4 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v4
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if:   ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set versions
        run : |
          set -x
          VERSION=$(cat version.txt | sed "s/^v//" )
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          REVISION=$(echo $VERSION | cut -d. -f3)
          echo "MAJOR=${MAJOR}" >> $GITHUB_ENV
          echo "MINOR=${MINOR}" >> $GITHUB_ENV
          echo "REVISION=${REVISION}" >> $GITHUB_ENV
      - run: echo $MAJOR
      - name: Docker meta
        id: seccubus_github_pages # you'll use this in the next step
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            mrseccubus/github-pages
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=${{ env.MAJOR }}
            type=raw,value=${{ env.MAJOR }}.${{ env.MINOR }}
            type=raw,value=${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.REVISION }}
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.url=https://github.com/MrSeccubus/github-pages
            org.opencontainers.image.source=https://github.com/MrSeccubus/github-pages
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.seccubus_github_pages.outputs.tags }}
          labels: ${{ steps.seccubus_github_pages.outputs.labels }}
